//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeTelegramBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeTelegramBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to afternoon,midday.
        /// </summary>
        internal static string AfternoonDefinition {
            get {
                return ResourceManager.GetString("AfternoonDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /help - available commands
        ////info - info about this bot
        ////weather - gives you a weather forecast
        ////switch - change state of objects at home.
        /// </summary>
        internal static string AvailableCommands {
            get {
                return ResourceManager.GetString("AvailableCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kharkiv,ua.
        /// </summary>
        internal static string DefaultWeatherCity {
            get {
                return ResourceManager.GetString("DefaultWeatherCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process this command, please see list of available commands using /help.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evening.
        /// </summary>
        internal static string EveningDefinition {
            get {
                return ResourceManager.GetString("EveningDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! I am Home Automation Telegram Bot. I can assist you in controlling your house and getting useful information. My version is .
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string InPreposition {
            get {
                return ResourceManager.GetString("InPreposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        internal static string MetersPerSecond {
            get {
                return ResourceManager.GetString("MetersPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to night,midnight.
        /// </summary>
        internal static string MidnightDefinition {
            get {
                return ResourceManager.GetString("MidnightDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to morning.
        /// </summary>
        internal static string MorningDefinition {
            get {
                return ResourceManager.GetString("MorningDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        internal static string NowDefinition {
            get {
                return ResourceManager.GetString("NowDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hPa.
        /// </summary>
        internal static string PressureUnits {
            get {
                return ResourceManager.GetString("PressureUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /switch command requires an object and an action.
        ///Example: /switch light off.
        /// </summary>
        internal static string SwitchDesc {
            get {
                return ResourceManager.GetString("SwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        internal static string TomorrowDefinition {
            get {
                return ResourceManager.GetString("TomorrowDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /weather command requires day
        ///Example: /weather tomorrow.
        /// </summary>
        internal static string WeatherDesc {
            get {
                return ResourceManager.GetString("WeatherDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
    }
}
